# Generated by Django 3.1.3 on 2020-11-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(max_length=200)),
                ('ip_address', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('operating_system', models.CharField(choices=[('UB', 'Ubuntu'), ('CE', 'CentOS'), ('FE', 'Fedora IOT')], default='UB', max_length=2)),
                ('metric_arp', models.BooleanField(default=True)),
                ('metric_bcache', models.BooleanField(default=True)),
                ('metric_bonding', models.BooleanField(default=True)),
                ('metric_boottime', models.BooleanField(default=True)),
                ('metric_conntrack', models.BooleanField(default=True)),
                ('metric_cpu', models.BooleanField(default=True)),
                ('metric_cpufreq', models.BooleanField(default=True)),
                ('metric_diskstats', models.BooleanField(default=True)),
                ('metric_edac', models.BooleanField(default=True)),
                ('metric_entropy', models.BooleanField(default=True)),
                ('metric_exec', models.BooleanField(default=True)),
                ('metric_filefd', models.BooleanField(default=True)),
                ('metric_filesystem', models.BooleanField(default=True)),
                ('metric_hwmon', models.BooleanField(default=True)),
                ('metric_infiniband', models.BooleanField(default=True)),
                ('metric_ipvs', models.BooleanField(default=True)),
                ('metric_loadavg', models.BooleanField(default=True)),
                ('metric_mdadm', models.BooleanField(default=True)),
                ('metric_meminfo', models.BooleanField(default=True)),
                ('metric_netclass', models.BooleanField(default=True)),
                ('metric_netdev', models.BooleanField(default=True)),
                ('metric_netstat', models.BooleanField(default=True)),
                ('metric_nfs', models.BooleanField(default=True)),
                ('metric_nfsd', models.BooleanField(default=True)),
                ('metric_pressure', models.BooleanField(default=True)),
                ('metric_rapl', models.BooleanField(default=True)),
                ('metric_schedstat', models.BooleanField(default=True)),
                ('metric_sockstat', models.BooleanField(default=True)),
                ('metric_softnet', models.BooleanField(default=True)),
                ('metric_stat', models.BooleanField(default=True)),
                ('metric_textfile', models.BooleanField(default=True)),
                ('metric_thermal_zone', models.BooleanField(default=True)),
                ('metric_time', models.BooleanField(default=True)),
                ('metric_timex', models.BooleanField(default=True)),
                ('metric_udp_queues', models.BooleanField(default=True)),
                ('metric_uname', models.BooleanField(default=True)),
                ('metric_vmstat', models.BooleanField(default=True)),
                ('metric_xfs', models.BooleanField(default=True)),
                ('metric_zfs', models.BooleanField(default=True)),
            ],
        ),
    ]
