# Generated by Django 3.1.3 on 2021-01-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='location',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='port_number',
            field=models.CharField(default=443, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endpoint',
            name='protocol',
            field=models.CharField(choices=[('S', 'HTTPS'), ('P', 'HTTP')], default='S', max_length=2),
        ),
    ]
