# Generated by Django 3.1.5 on 2021-03-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_auto_20210121_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='SSH_rsa_pub',
            field=models.CharField(default=2423423423, max_length=500),
            preserve_default=False,
        ),
    ]
