# Generated by Django 3.1.5 on 2021-03-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_endpoint_exclude_metric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='SSH_rsa_pub',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='exclude_metric',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
