# Generated by Django 3.1.3 on 2021-03-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0006_auto_20210310_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='operating_system',
            field=models.CharField(choices=[('UB', 'Ubuntu'), ('CE', 'CentOS'), ('FE', 'Fedora IOT'), ('PI', 'Raspberry Pi 4')], default='PI', max_length=2),
        ),
    ]
